import hashlib
import json
from typing import Any, Callable, Dict, List, Optional, Tuple

from nala.athomic.config import get_settings
from nala.athomic.config.schemas.context.context_config import ContextSettings
from nala.athomic.context.execution import ExecutionContext
from nala.athomic.observability.log import get_logger

logger = get_logger(__name__)


def _default_arg_serializer(obj: Any) -> str:
    """Fallback serializer for non-JSON-serializable function arguments."""
    try:
        return repr(obj)
    except Exception:
        return f"<unserializable type: {type(obj).__name__}>"


class ContextKeyGenerator:
    """A centralized service for creating consistent and context-sensitive keys.

    This class standardizes key generation for features like caching, locking,
    and rate limiting. It automatically prepends keys with a static prefix and
    contextual information (e.g., tenant ID) based on the application's
    configuration, ensuring key consistency and multi-tenancy support.

    Attributes:
        settings (ContextSettings): The context configuration settings.
        static_prefix (str): A global prefix for all generated keys (e.g., 'nala').
        use_tenant (bool): If True, the tenant ID is included in the key.
        use_user (bool): If True, the user ID is included in the key.
        separator (str): The character used to separate key parts.
        namespace (str): The specific namespace for this key generator instance.
    """

    def __init__(
        self,
        *,
        namespace: Optional[str] = None,
        settings: Optional[ContextSettings] = None,
    ):
        """Initializes the ContextKeyGenerator.

        Args:
            namespace (Optional[str]): A specific namespace for the keys
                generated by this instance. Overrides the default
                namespace from settings if provided.
            settings (Optional[ContextSettings]): The context configuration
                settings. If not provided, global settings are used.
        """
        self.settings: ContextSettings = settings or get_settings().context

        self.static_prefix: str = self.settings.static_prefix or "nala"

        self.use_tenant: bool = (
            self.settings.multi_tenancy_enabled
            if self.settings.multi_tenancy_enabled is not None
            else True
        )
        self.use_user: bool = (
            self.settings.use_user_uid
            if self.settings.use_user_uid is not None
            else False
        )

        self.separator: str = self.settings.separator or ":"
        self.namespace: str = namespace or self.settings.namespace or "default"

    def _get_context_prefix(self) -> str:
        """Builds the contextual part of a key from the current ExecutionContext.

        It checks the configuration (`use_tenant`, `use_user`) and the active
        ExecutionContext to assemble a prefix, such as 'tenant1:user42'.

        Returns:
            str: The context-aware part of the key.
        """
        current_context = ExecutionContext()
        parts: List[str] = []

        if self.use_tenant and current_context.tenant_id:
            parts.append(current_context.tenant_id)

        if self.use_user and current_context.user_id:
            parts.append(current_context.user_id)

        return self.separator.join(parts)

    def generate(self, *key_parts: Any) -> str:
        """Generates a final key from multiple parts with context and namespace.

        The final key structure is:
        `static_prefix:context_prefix:namespace:part1:part2:...`

        Args:
            *key_parts (Any): A variable number of logical parts to be
                appended to the key.

        Returns:
            str: The fully constructed, context-aware key.
        """
        context_prefix = self._get_context_prefix()

        all_parts = [
            self.static_prefix,
            context_prefix,
            self.namespace,
            *(str(p) for p in key_parts if p is not None),
        ]

        return self.separator.join(filter(None, all_parts))

    def generate_for_function(self, func: Callable, args: Tuple, kwargs: Dict) -> str:
        """Generates a unique and deterministic key for a function call.

        This method is ideal for function caching decorators. It creates a stable
        key by combining the function's qualified name with a SHA256 hash of its
        serialized arguments, ensuring that the same call always produces the
        same key.

        Args:
            func (Callable): The function being called.
            args (Tuple): The positional arguments passed to the function.
            kwargs (Dict): The keyword arguments passed to the function.

        Returns:
            str: A unique key representing the specific function call.
        """
        function_name = getattr(func, "__qualname__", str(func))

        try:
            kwargs_tuple = tuple(sorted(kwargs.items()))
            combined_args = (args, kwargs_tuple)
            serialized_args = json.dumps(
                combined_args, sort_keys=True, default=_default_arg_serializer
            )
            hashed_args = hashlib.sha256(serialized_args.encode("utf-8")).hexdigest()
        except Exception:
            logger.exception("Error serializing/hashing key arguments.")
            hashed_args = "hashing_error"

        return self.generate(function_name, hashed_args)
