# src/nala/athomic/config/schemas/context/context_config.py
from typing import List, Optional

from pydantic import BaseModel, ConfigDict, Field


class ContextSettings(BaseModel):
    """Defines the configuration for the context management system.

    These settings control two main aspects of the framework:
    1. The behavior of the `ContextKeyGenerator`, which creates standardized
       keys for features like caching, locking, and rate limiting.
    2. The context propagation mechanism, specifying which variables from the
       `ExecutionContext` are automatically passed to background tasks and events.

    Attributes:
        multi_tenancy_enabled (Optional[bool]): Enables multi-tenancy features.
        static_prefix (Optional[str]): A static prefix for all generated keys.
        separator (Optional[str]): The character to separate key parts.
        namespace (Optional[str]): The default namespace for grouping keys.
        use_user_uid (Optional[bool]): Toggles inclusion of the user ID in keys.
        propagated_vars (List[str]): A list of context variable names to propagate.
    """

    model_config = ConfigDict(
        extra="ignore", validate_assignment=True, populate_by_name=True
    )

    multi_tenancy_enabled: Optional[bool] = Field(
        default=False,
        alias="MULTI_TENANCY_ENABLED",
        description="If True, enables features that depend on multi-tenancy, like automatic tenant ID filtering in data repositories.",
    )

    static_prefix: Optional[str] = Field(
        default="nala",
        alias="STATIC_PREFIX",
        description="A static string prepended to all keys generated by ContextKeyGenerator.",
    )

    separator: Optional[str] = Field(
        default=":",
        alias="SEPARATOR",
        description="The character used to separate parts of a generated key (e.g., ':').",
    )

    namespace: Optional[str] = Field(
        default="default",
        alias="NAMESPACE",
        description="The default namespace used by ContextKeyGenerator for grouping keys.",
    )

    use_user_uid: Optional[bool] = Field(
        default=False,
        alias="USE_USER_UID",
        description="If True, includes the user's unique ID as part of the key generated by ContextKeyGenerator.",
    )

    propagated_vars: List[str] = Field(
        default_factory=lambda: [
            "request_id",
            "trace_id",
            "tenant_id",
            "span_id",
            "user_id",
            "role",
            "locale",
            "correlation_id",
            "feature_flags",
        ],
        alias="PROPAGATED_VARS",
        description="A list of context variable names that should be automatically captured and passed to background tasks or asynchronous events.",
    )
