from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from .tools import ToolCall


class TokenUsage(BaseModel):
    """
    Standardized usage metrics for LLM generation.
    """

    prompt_tokens: int = Field(0, description="Tokens consumed by the input prompt.")
    completion_tokens: int = Field(0, description="Tokens generated in the output.")
    total_tokens: int = Field(0, description="Total tokens consumed.")


class LLMRequest(BaseModel):
    """
    This class defines a unified interface for making requests to various Large Language Model
    providers. It encapsulates all necessary parameters and configurations needed to generate
    text completions or chat responses.

    Attributes:
        prompt (str): The input text prompt to send to the LLM for generation.
        model (Optional[str]): The specific model name/identifier to use for generation.
            If None, the provider's default model will be used.
        system_message (Optional[str]): System-level instructions that define the AI's
            behavior and context for the conversation.
        temperature (Optional[float]): Controls randomness in generation (0.0-1.0).
            Lower values make output more deterministic, higher values more creative.
        max_tokens (Optional[int]): Maximum number of tokens to generate in the response.
            Controls the length of the generated text.
        stop_sequences (Optional[List[str]]): List of strings that will stop generation
            when encountered. Useful for controlling output format and boundaries.
        extra_params (Dict[str, Any]): Additional provider-specific parameters that
            don't fit into the standard schema. Defaults to empty dictionary.

    Example:
        >>> request = LLMRequest(
        ...     prompt="Explain quantum computing",
        ...     model="gpt-4",
        ...     temperature=0.7,
        ...     max_tokens=500
        ... )
    """

    prompt: str
    model: Optional[str] = None
    system_message: Optional[str] = None
    temperature: Optional[float] = None
    max_tokens: Optional[int] = None
    stop_sequences: Optional[List[str]] = None
    extra_params: Dict[str, Any] = Field(default_factory=dict)


class LLMResponse(BaseModel):
    """
    Standardized response from any LLM Provider.
    Encapsulates both text content and potential tool execution requests.
    """

    content: Optional[str] = Field(
        None, description="The text content generated by the model."
    )
    tool_calls: List[ToolCall] = Field(
        default_factory=list, description="List of tools the model wants to execute."
    )
    usage: TokenUsage = Field(
        default_factory=TokenUsage,
        description="Token usage statistics.",
    )
    finish_reason: str = Field(
        ...,
        description="Why the generation stopped (e.g., stop, length, tool_calls).",
    )
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional metadata (e.g., cache_hit, latency, provider specifics).",
    )
    model: str = Field(..., description="The specific model used for generation.")

    @property
    def has_tool_calls(self) -> bool:
        """Returns True if the model requested any tool executions."""
        return len(self.tool_calls) > 0


class LLMResponseChunk(BaseModel):
    """
    Represents a single, incremental chunk of the response during streaming.
    """

    content_delta: Optional[str] = Field(
        None, description="The incremental text content (token delta)."
    )
    tool_calls_delta: List[ToolCall] = Field(
        default_factory=list,
        description="Incremental list of tool calls (usually only on the final chunk or first block).",
    )
    # The final chunk may optionally contain usage and finish_reason.
    usage: Optional[TokenUsage] = Field(
        None,
        description="Token usage statistics (usually only present on the final chunk).",
    )
    finish_reason: Optional[str] = Field(
        None,
        description="Why the generation stopped (e.g., stop, length, tool_calls).",
    )
    model: Optional[str] = Field(
        None, description="The specific model used for generation."
    )
