# src/nala/athomic/ai/agents/executors/protocol.py
from typing import List, Protocol, runtime_checkable

from nala.athomic.ai.schemas import ToolCall, ToolOutput


@runtime_checkable
class ToolExecutorProtocol(Protocol):
    """
    Defines the contract for executing tool calls generated by an LLM.

    This abstraction allows different execution strategies (e.g., in-process,
    background task, distributed worker) to be used interchangeably by the Agent Runtime.
    """

    async def execute_batch(self, tool_calls: List[ToolCall]) -> List[ToolOutput]:
        """
        Executes a batch of tool calls and returns their results.

        Args:
            tool_calls: A list of tool invocation requests (name, arguments, id).

        Returns:
            A list of ToolOutput objects containing results or formatted error messages.
            The order of outputs does not strictly need to match inputs, as mapping
            is done via 'tool_call_id', but maintaining order is recommended.
        """
        ...
