from typing import Optional

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Data Transfer Object for incoming chat requests from the user.

    Attributes:
        employee_id: The unique identifier of the employee making the request.
        message: The natural language message input from the user.
        session_id: An optional identifier to maintain conversation state across multiple turns.
    """

    employee_id: str = Field(
        ...,
        description="The unique identifier of the employee.",
    )
    message: str = Field(
        ...,
        description="The natural language message from the user.",
    )
    session_id: Optional[str] = Field(
        None,
        description="Optional session identifier for conversation memory.",
    )


class ChatResponse(BaseModel):
    """Data Transfer Object for outgoing chat responses from the agent.

    Attributes:
        reply: The natural language response generated by the HR agent.
        session_id: The session identifier to be used in subsequent requests to maintain context.
    """

    reply: str = Field(
        ...,
        description="The response generated by the agent.",
    )
    session_id: str = Field(
        ...,
        description="The session identifier for the conversation.",
    )
